FROM node:alpine

ENV ENV production

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

COPY ./ ./

RUN ls -a

RUN npm install
RUN npm run build
# RUN npm run minify:html

EXPOSE 8080

CMD ["npm", "run", "start"]
